### ISSUE TITLE
TypeError: azure is not a function

### ISSUE THREAD

**Issue by p-rk** [ThibautMarechal/turborepo-remote-cache#511]
While uploading the artifacts `/turbo/api/v8/artifacts/` it is throwing 500 error.

**Comment by ThibautMarechal** [comment]
Hi @p-rk thanks for the issue, I'll fix this as soon as possible.

**Comment by ThibautMarechal** [comment]
Fixed and available in [1.13.1](https://github.com/ThibautMarechal/turborepo-remote-cache/releases/tag/v1.13.1)
